print.bintest<-function(x,...){
  cat("\nMultiple comparisons of binomial proportions:")
  cat("\n=============================================\n")
  print(x$mc)
  cat("\nRow names specifies currently compared treatments in respective row.\n")
  cat("--------------------------------------------------------------------\n")
  cat("\nConfidence intervals for probabilities:")
  cat("\n=============================================\n")
  cat("\nThe estimate is computed for column named:",x$obs_variable)
  cat("\n\n")
  print(x$CI)
  cat("-----------------------------------\n")
  cat("\nError bar lengths:")
  cat("\n=============================================\n")
  print(x$errbars)
  cat("-----------------------\n")
}
