print.bintest<-function(x,...){
  cat("\n Multiple comparisons of binomial proportions:")
  cat("\n =============================================\n")
  print(x$mc)
  cat("\n Numbers in first two columns depicts row numbers in input table.\n")
  cat(" -----------------------------------------------------------------\n")
  cat("\n Confidence intervals for probabilities:")
  cat("\n =============================================\n")
  cat("\n The estimate is computed for column named:",x$obs_variable)
  cat("\n\n")
  print(x$CI)
  cat(" -----------------------------------\n")
  cat("\n Error bar lengths:")
  cat("\n =============================================\n")
  print(x$errbars)
  cat(" -----------------------\n")
}
